### PR TITLE
fix concrete setters for optional in staged required only builder

### LINKED ISSUE #204: addConcreteSettersForOptional doesn't add concrete setter on staged builders
`addConcreteSettersForOptional` adds a concrete setter on standard builders, but not on staged (required only ?) builders.

Adapting the test class `io.soabase.recordbuilder.test.staged.OptionalListStaged` like mentioned in issue #184 (adding `addConcreteSettersForOptional = true`) doesn't allow the following code:

`OptionalListStagedBuilder.builder().a(1).c(1.1).f("ffff").b("bbbb").d(List.of(Instant.EPOCH)).e("eeee").build();`

where method `b` gets a concrete `String` as argument.

### PR DESCRIPTION
**Pull request by gvdenbro**
fixes #204

### CODE REVIEW

File: record-builder-test/src/main/java/io/soabase/recordbuilder/test/staged/OptionalListStaged.java [hunk 1]
```diff
@@ -23,6 +23,6 @@
 import java.util.Optional;
 
 @RecordBuilder
-@RecordBuilder.Options(builderMode = RecordBuilder.BuilderMode.STAGED_REQUIRED_ONLY, interpretNotNulls = true, useImmutableCollections = true)
+@RecordBuilder.Options(builderMode = RecordBuilder.BuilderMode.STAGED_REQUIRED_ONLY, interpretNotNulls = true, useImmutableCollections = true, addConcreteSettersForOptional = true)
```
Comment (Randgalt) [inline record-builder-test/src/main/java/io/soabase/recordbuilder/test/staged/OptionalListStaged.java:26]: Please make this a separate class so we have both tests.

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java [hunk 2]
```diff
@@ -220,6 +220,10 @@ private boolean isRequiredStage(RecordClassType recordComponent) {
             return false;
         }
 
+        if (metaData.addConcreteSettersForOptional()) {
```
Comment (Randgalt) [inline record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:223]: This is wrong. The real fix for this would be in `addStagedBuilderClasses()`. When the non-required stage methods are being added `addConcreteSettersForOptional` needs to be checked so that an additional method, similar to `add1ConcreteOptionalSetterMethod`, is added to the stage being built.

File: record-builder-test/src/main/java/io/soabase/recordbuilder/test/staged/OptionalListStaged.java (hunk 1 above)
Comment (gvdenbro) [reply record-builder-test/src/main/java/io/soabase/recordbuilder/test/staged/OptionalListStaged.java:26]: will do

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java (hunk 2 above)
Comment (gvdenbro) [reply record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:223]: clear.

**Comment by gvdenbro** [comment]
added a new test case and handled the addition of the method in the appropriate place.
there's a bit of code duplication. not sure if it's worth tackling it.
also i wonder about the commit history (2 commits basically). don't know if you're fine with that.

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java [hunk 3]
```diff
@@ -266,6 +266,28 @@ private void addStagedBuilderClasses() {
                             .addModifiers(Modifier.PUBLIC, Modifier.DEFAULT).addParameter(parameterSpecBuilder.build())
                             .addCode(codeBlock).returns(builderClassType.typeName()).build();
                     classBuilder.addMethod(methodSpec);
+
+                    if (metaData.addConcreteSettersForOptional()) {
+
```
Comment (Randgalt) [inline record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:271]: nit: remove blank line here and below

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java [hunk 4]
```diff
@@ -266,6 +266,28 @@ private void addStagedBuilderClasses() {
...
+                        var optionalType = OptionalType.fromClassType(optionalComponent);
```
Comment (Randgalt) [inline record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:272]: Let's move this into a separate method similar in name to `add1ConcreteOptionalSetterMethod()`

**Comment by Randgalt** [comment]
Please squash commits

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java (hunk 3 above)
Comment (gvdenbro) [reply record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:271]: ok

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java (hunk 4 above)
Comment (gvdenbro) [reply record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:272]: ok

**Comment by gvdenbro** [comment]
> Please squash commits

ok

**Comment by gvdenbro** [comment]
updated code according to remarks and squashed the commits

**Comment by Randgalt** [comment]
Thank you for the PR!
