### PR TITLE
Options/changes so that Jacoco checks don't fail

### LINKED ISSUE #87: exclude from Jacoco coverage
Jacoco exclusion works by having` @Generated` annotation in bytecode, but the default `javax.annotation.processing.Generated` in only on source level.
https://github.com/jacoco/jacoco/blob/046ba52e9fd1288cf121fd1013c9019d71946954/org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AnnotationGeneratedFilter.java

Can I add a custom annotation inside record-builder?

### PR DESCRIPTION
**Pull request by Randgalt**
- Added new optional Annotation `@RecordBuilderGenerated` - Jacoco ignores
classes with any annotation names "\*Generated\*" but it needs to be class retained.
For backward compatibility this annotation is not added by default (though it's been
added to `@RecordBuilderFull`). There is a new option to enable it.
- The from with method now uses an internal static class instead of an anonymous
inner class so that the annotation can be on this as well. This new class's name
is configurable in the options.

Thanks to user @madisparn for initial PR and issue report.

Fixes #87

### CODE REVIEW

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java [hunk 1]
```diff
@@ -560,63 +567,83 @@ private CodeBlock buildCodeBlock() {
...
-                    public String p1() {
-                        return from.p1();
-                    }
-
-                    @Override
-                    public String p2() {
-                        return from.p2();
-                    }
-                };
+            private static final class _FromWith implements MyRecordBuilder.With {
```
Comment (madisparn) [inline record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:583]: Class name will be `MyRecordBuilder_FromWith` ?

**Comment by madisparn** [comment]
Looks good

File: record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java (hunk 1 above)
Comment (Randgalt) [reply record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:583]: `MyRecordBuilder._FromWith` - The `_` is commonly used to hide internal names. But, I'm open to other names.

Comment (madisparn) [reply record-builder-processor/src/main/java/io/soabase/recordbuilder/processor/InternalRecordBuilderProcessor.java:583]: `_FromWith` is good, I just did not read the code properly
